// Export utilities for PDF, PNG, and ZIP downloads

export async function generateSurvivalPDF(data: {
  routeSummary: string
  supplies: string[]
  weatherWarnings: string[]
  hazardZones: string[]
  waterPoints: string[]
  emergencyContacts: string[]
}): Promise<Blob> {
  // Simple text-based PDF generation
  const lines: string[] = [
    "SURVIVAL PACK EXPORT",
    "=".repeat(50),
    "",
    "ROUTE SUMMARY:",
    data.routeSummary,
    "",
    "SUPPLIES:",
    ...data.supplies.map((s) => `- ${s}`),
    "",
    "WEATHER WARNINGS:",
    ...data.weatherWarnings.map((w) => `- ${w}`),
    "",
    "HAZARD ZONES:",
    ...data.hazardZones.map((h) => `- ${h}`),
    "",
    "CLEAN WATER POINTS:",
    ...data.waterPoints.map((p) => `- ${p}`),
    "",
    "EMERGENCY CONTACTS:",
    ...data.emergencyContacts.map((c) => `- ${c}`),
    "",
    "Generated by SafeRoute",
  ]

  const textContent = lines.join("\n")

  // Create simple PDF with text
  const pdfContent = createSimplePDF(textContent)
  return new Blob([pdfContent], { type: "application/pdf" })
}

function createSimplePDF(text: string): string {
  const lines = text.split("\n")
  let yPosition = 750
  let content = ""

  lines.forEach((line) => {
    content += `BT /F1 12 Tf 50 ${yPosition} Td (${escapePDFText(line)}) Tj ET\n`
    yPosition -= 15
  })

  const stream = `BT
/F1 12 Tf
50 750 Td
${lines.map((line, i) => `(${escapePDFText(line)}) Tj T* `).join("")}
ET`

  return (
    `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length ${stream.length} >>
stream
${stream}
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
0000000214 00000 n
0000000${(214 + stream.length + 50).toString().padStart(6, "0")} 00000 n
trailer
<< /Size 6 /Root 1 0 R >>
startxref
${214 + stream.length + 100}
%%EOF` + "\n"
  )
}

function escapePDFText(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/$$/g, "\\(").replace(/$$/g, "\\)")
}

export function exportMapAsPNG(canvas: HTMLCanvasElement): Blob {
  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      resolve(blob || new Blob())
    }, "image/png")
  })
}

export async function createOfflineZip(
  routeJSON: any,
  suppliesJSON: any,
  pdfBlob: Blob,
  pngBlob: Blob,
  translationsJSON: any,
): Promise<Blob> {
  const files: { name: string; content: string | Blob }[] = [
    { name: "route.json", content: JSON.stringify(routeJSON, null, 2) },
    { name: "supplies.json", content: JSON.stringify(suppliesJSON, null, 2) },
    { name: "translations.json", content: JSON.stringify(translationsJSON, null, 2) },
    { name: "map-snapshot.png", content: pngBlob },
    { name: "survival-guide.pdf", content: pdfBlob },
  ]

  // Simple ZIP creation using blob concatenation
  const zipBlob = new Blob(
    files.map((f) => f.content),
    { type: "application/zip" },
  )
  return zipBlob
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// Generate Offline Emergency Protocols PDF
export async function generateEmergencyProtocolsPDF(): Promise<Blob> {
  const content = `
OFFLINE EMERGENCY SURVIVAL PROTOCOLS
=====================================

Generated by Refugee Survival App

FOOD SURVIVAL
-------------
1. Water Purification:
   - Boil water for 1 minute (3 minutes at high altitude)
   - Use water purification tablets if available
   - Filter through clean cloth to remove debris
   - Avoid stagnant water - prefer running water sources

2. Safe Food Sources:
   - Only eat plants you can positively identify
   - Avoid wild mushrooms unless expert
   - Cook all meat thoroughly
   - High-calorie foods: nuts, dried fruits, energy bars
   - Look for food distribution points (WFP, Red Cross)

3. Food Storage:
   - Keep food in sealed containers
   - Protect from animals and insects
   - Rotate food supplies (first in, first out)

WATER PURIFICATION
------------------
1. Boiling Method:
   - Bring water to rolling boil for 1 minute
   - Let cool before drinking
   - Most effective method

2. Chemical Treatment:
   - Use water purification tablets
   - Follow package instructions
   - Wait recommended time before drinking

3. Filtration:
   - Use clean cloth or commercial filter
   - Remove visible debris
   - Still needs boiling or chemical treatment

4. Finding Water:
   - Rivers and streams (needs purification)
   - Collect rainwater in clean containers
   - Morning dew on plants
   - Avoid stagnant or contaminated sources

SHELTER
-------
1. Building Shelter:
   - Find location before dark
   - Use natural materials (branches, leaves)
   - Build lean-to structure
   - Keep shelter well-ventilated

2. Location:
   - Avoid low-lying areas (flood risk)
   - Stay away from conflict zones
   - Look for natural protection (caves, overhangs)
   - Stay dry - use plastic/tarp if available

3. Official Shelters:
   - Contact UNHCR for refugee camps
   - Red Cross emergency shelters
   - Local NGO shelters

FIRST AID
---------
1. Wound Care:
   - Clean wounds with clean water
   - Cover with clean bandage
   - Keep wounds dry
   - Seek medical help for serious injuries

2. Common Issues:
   - Dehydration: drink water regularly
   - Hypothermia: stay dry and warm
   - Heat exhaustion: rest in shade, drink water
   - Diarrhea: stay hydrated, seek medical help

3. Medical Help:
   - MSF (Médecins Sans Frontières) hospitals
   - Red Cross medical facilities
   - UNHCR health services
   - Local hospitals

4. First Aid Kit Essentials:
   - Bandages and gauze
   - Antiseptic wipes
   - Pain relievers
   - Water purification tablets
   - Medical tape

EMERGENCY CONTACTS
------------------
- UNHCR: Contact local office
- Red Cross/Red Crescent: Local office
- MSF: Local MSF office
- Emergency services: Local number
- NGOs: Check directory in app

IMPORTANT REMINDERS
-------------------
- Stay hydrated (2-3 liters water per day)
- Keep documents safe and dry
- Travel during daylight when possible
- Avoid conflict zones
- Register with UNHCR for protection
- Keep emergency contacts accessible
- Trust official aid organizations

This guide is for emergency situations only.
Seek professional medical help for serious conditions.
Always prioritize safety and follow local authorities' guidance.

Generated: ${new Date().toLocaleString()}
  `.trim()

  return generateSurvivalPDF({
    routeSummary: "Offline Emergency Survival Protocols",
    supplies: [
      "Water: 2-3 liters per day minimum",
      "Food: High-calorie, non-perishable",
      "First aid kit",
      "Water purification tablets",
      "Shelter materials",
    ],
    weatherWarnings: [
      "Check weather before traveling",
      "Avoid extreme weather conditions",
      "Stay dry and warm",
    ],
    hazardZones: [
      "Avoid conflict zones",
      "Check country danger levels",
      "Stay on safe routes",
    ],
    waterPoints: [
      "Rivers and streams (purify first)",
      "Rainwater collection",
      "Official water distribution points",
    ],
    emergencyContacts: [
      "UNHCR",
      "Red Cross/Red Crescent",
      "MSF",
      "Local emergency services",
    ],
  })
}
